name: transparente
channels:
  - conda-forge
dependencies:
  - tqdm
  - imageio
  - llvmlite
  - scipy
  - scikit-learn
  - joblib
  - rembg
  - packaging
  - platformdirs
  - python=3.11
  - tk
  - typing-extensions
  - networkx
  - pillow
  - protobuf
  - pymatting
  - pooch
  - tifffile
  - numpy
  - numba
  - opencv
  - cmake
  - scikit-image
  - onnxruntime
  - pylint
  - python.app
  - pyinstaller
  - dmgbuild

# macOS: brew install potrace


prefix: /Users/dani/miniforge3/envs/transparente
